SUMMARY_TEMPLATE = (
    "You are an expert document summarizer.\n\n"
    "Task: Read the provided document text and produce a clear, concise summary.\n\n"
    "Instructions:\n"
    "- Identify key topics.\n"
    "- Extract important insights.\n"
    "- Avoid repetition.\n"
    "- Maintain logical flow.\n"
    "- Use simple language.\n\n"
    "Output format:\n"
    "Summary:\n"
    "<clear summary>\n\n"
    "Key Points:\n"
    "- point 1\n"
    "- point 2\n"
    "- point 3\n"
)